services:
  - type: web
    name: smartscan-ai-node
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    plan: starter
    envVars:
      - key: PORT
        value: 3001
